#!/bin/bash

regex='@einfochips\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
    echo "Your email $email satisfies git policy"
    exit 0
else 
    echo "Your email $email doesn't satisfy git policy"
    exit 1
fi